# Kafka Configuration
kafka.bootstrap.servers=localhost:9092
kafka.topic.dictionary=maszyny-slownik
kafka.application.id=machine-dictionary-app
kafka.processing.guarantee=at_least_once

# Dictionary Configuration
dictionary.path=src/main/resources/dictionary/machine_catalog.json